{
  "google/vit-base-patch16-224": {
    "status": "error",
    "output": "Loading vision model: google/vit-base-patch16-224...\nVision model loaded in 13.61s\nParameters: 86,389,248\nMemory usage: 807.0MB\n",
    "error": "2025-07-09 19:30:16.915814: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.\n2025-07-09 19:30:18.084920: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.\nSome weights of ViTModel were not initialized from the model checkpoint at google/vit-base-patch16-224 and are newly initialized: ['vit.pooler.dense.bias', 'vit.pooler.dense.weight']\nYou should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.\nFast image processor class <class 'transformers.models.vit.image_processing_vit_fast.ViTImageProcessorFast'> is available for this model. Using slow image processor class. To use the fast image processor class set `use_fast=True`.\nTraceback (most recent call last):\n  File \"<string>\", line 38, in <module>\n  File \"C:\\Users\\mateo\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\transformers\\image_processing_utils.py\", line 42, in __call__\n    return self.preprocess(images, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\mateo\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\transformers\\utils\\generic.py\", line 854, in wrapper\n    return func(*args, **valid_kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\mateo\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\transformers\\models\\vit\\image_processing_vit.py\", line 262, in preprocess\n    self.resize(image=image, size=size_dict, resample=resample, input_data_format=input_data_format)\n  File \"C:\\Users\\mateo\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\transformers\\models\\vit\\image_processing_vit.py\", line 142, in resize\n    return resize(\n           ^^^^^^^\n  File \"C:\\Users\\mateo\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\transformers\\image_transforms.py\", line 369, in resize\n    do_rescale = _rescale_for_pil_conversion(image)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\mateo\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\transformers\\image_transforms.py\", line 151, in _rescale_for_pil_conversion\n    raise ValueError(\nValueError: The image to be converted to a PIL image contains values outside the range [0, 1], got [-4.4564924240112305, 4.67672061920166] which cannot be converted to uint8.\n"
  },
  "microsoft/swin-base-patch4-window7-224": {
    "status": "error",
    "output": "Loading vision model: microsoft/swin-base-patch4-window7-224...\nVision model loaded in 14.25s\nParameters: 86,743,224\nMemory usage: 803.3MB\n",
    "error": "2025-07-09 19:30:42.151188: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.\n2025-07-09 19:30:43.413513: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.\nUsing a slow image processor as `use_fast` is unset and a slow processor was saved with this model. `use_fast=True` will be the default behavior in v4.48, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with `use_fast=False`.\nTraceback (most recent call last):\n  File \"<string>\", line 38, in <module>\n  File \"C:\\Users\\mateo\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\transformers\\image_processing_utils.py\", line 42, in __call__\n    return self.preprocess(images, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\mateo\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\transformers\\utils\\generic.py\", line 854, in wrapper\n    return func(*args, **valid_kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\mateo\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\transformers\\models\\vit\\image_processing_vit.py\", line 262, in preprocess\n    self.resize(image=image, size=size_dict, resample=resample, input_data_format=input_data_format)\n  File \"C:\\Users\\mateo\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\transformers\\models\\vit\\image_processing_vit.py\", line 142, in resize\n    return resize(\n           ^^^^^^^\n  File \"C:\\Users\\mateo\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\transformers\\image_transforms.py\", line 369, in resize\n    do_rescale = _rescale_for_pil_conversion(image)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\mateo\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\transformers\\image_transforms.py\", line 151, in _rescale_for_pil_conversion\n    raise ValueError(\nValueError: The image to be converted to a PIL image contains values outside the range [0, 1], got [-3.9538285732269287, 4.274692535400391] which cannot be converted to uint8.\n"
  },
  "openai/clip-vit-base-patch32": {
    "status": "error",
    "output": "Loading vision model: openai/clip-vit-base-patch32...\nVision model loaded in 24.85s\nParameters: 151,277,313\nMemory usage: 833.9MB\n",
    "error": "2025-07-09 19:31:09.013571: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.\n2025-07-09 19:31:10.410774: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.\nTraceback (most recent call last):\n  File \"<string>\", line 34, in <module>\n  File \"C:\\Users\\mateo\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\transformers\\models\\clip\\processing_clip.py\", line 109, in __call__\n    image_features = self.image_processor(images, return_tensors=return_tensors, **image_processor_kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\mateo\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\transformers\\image_processing_utils.py\", line 42, in __call__\n    return self.preprocess(images, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\mateo\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\transformers\\models\\clip\\image_processing_clip.py\", line 325, in preprocess\n    image = self.resize(image=image, size=size, resample=resample, input_data_format=input_data_format)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\mateo\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\transformers\\models\\clip\\image_processing_clip.py\", line 191, in resize\n    return resize(\n           ^^^^^^^\n  File \"C:\\Users\\mateo\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\transformers\\image_transforms.py\", line 369, in resize\n    do_rescale = _rescale_for_pil_conversion(image)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\mateo\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\transformers\\image_transforms.py\", line 151, in _rescale_for_pil_conversion\n    raise ValueError(\nValueError: The image to be converted to a PIL image contains values outside the range [0, 1], got [-4.336886405944824, 4.630574703216553] which cannot be converted to uint8.\n"
  }
}